// Regenerate src/tables/oswald.js from scripts/fonts/Oswald.ttf using the
// PUBLIC buildWidthTable() API (so the prebuilt table stays in sync with it).
// Run: npm run gen:oswald
//
// To add another font: copy its .ttf into scripts/fonts/, point `font` at it,
// and write to a new src/tables/<name>.js — same three lines.
import opentype from 'opentype.js';
import { writeFileSync } from 'node:fs';
import { buildWidthTable, DEFAULT_CHARSET } from '../index.js';

const font = opentype.loadSync(
  new URL('./fonts/Oswald.ttf', import.meta.url).pathname
);
// measure(text) -> advance width per em (font-size 1), kerning on
const measure = (t) => font.getAdvanceWidth(t, 1, { kerning: true });

const raw = buildWidthTable(measure, { chars: DEFAULT_CHARSET });

const r = (n) => Math.round(n * 1e4) / 1e4;
const round = (o) =>
  Object.fromEntries(Object.entries(o).map(([k, v]) => [k, r(v)]));

const body =
  '// GENERATED by scripts/gen-oswald.mjs (npm run gen:oswald) — do not edit by hand.\n' +
  '// Oswald 400 width table, per em. table[char] = advance/em; adj[pair] = kern/ligature/em.\n' +
  'export const oswald = Object.freeze({\n' +
  `  fallback: ${r(raw.fallback)},\n` +
  `  table: ${JSON.stringify(round(raw.table))},\n` +
  `  adj: ${JSON.stringify(round(raw.adj))},\n` +
  '})\n';

writeFileSync(
  new URL('../src/tables/oswald.js', import.meta.url).pathname,
  body
);
console.log(
  `regenerated src/tables/oswald.js — ${Object.keys(raw.table).length} chars, ${Object.keys(raw.adj).length} pairs`
);
